interface guest {
    use types.{message, guest-configuration, error};

    /// Whenever this guest receives a message in one of the subscribed channels, the message is
    /// sent to this handler
    handler: func(ms: list<message>) -> result<_, error>;
}
