package wasi:messaging@0.2.0-draft;

world imports {
	import producer;
	import consumer;
}

world imports-request-reply {
	include imports;
	import request-reply;
}

world messaging {
	include imports;
	export incoming-handler;
}