package wasi:messaging@0.2.0-draft;

world imports {
	import producer;
}

world imports-request-reply {
	include imports;
	import request-reply;
}

world messaging-request-reply {
	include imports-request-reply;
	export incoming-handler;
}

world messaging-core {
	include imports;
	export incoming-handler;
}
